services:

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: cloudshop:1.1
    ports:
      - "8082:80"

  backend:
    image: nginx:1.31.3
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.4

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pcloudshoproot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mysql_data:
